### ISSUE TITLE
unable to run the project after following the instructions on docs 

### ISSUE THREAD

**Issue by omarbenzi** [obytes/react-native-template-obytes#221]
java -version
openjdk version "11.0.16.1" 2022-08-12 LTS
OpenJDK Runtime Environment Microsoft-40648 (build 11.0.16.1+1-LTS)
OpenJDK 64-Bit Server VM Microsoft-40648 (build 11.0.16.1+1-LTS, mixed mode)
----------------------------------------------------------------------------

gradle -version

------------------------------------------------------------
Gradle 8.4
------------------------------------------------------------

Build time:   2023-10-04 20:52:13 UTC
Revision:     e9251e572c9bd1d01e503a0dfdf43aedaeecdc3f

Kotlin:       1.9.10
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          11.0.16.1 (Microsoft 11.0.16.1+1-LTS)
OS:           Windows 10 10.0 amd64

------------------------------------------------

# error:
C:\Users\react\testing\MyApp>pnpm android

> myapp@0.0.1 android C:\Users\react\testing\MyApp
> cross-env EXPO_NO_DOTENV=1 expo run:android

› Building app...
Configuration on demand is an incubating feature.

> Configure project :app
 ??  Applying gradle plugin 'expo-dev-launcher-gradle-plugin' (expo-dev-launcher@2.4.13)

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not determine the dependencies of null.
   > SDK location not found. Define a valid SDK location with an ANDROID_HOME environment variable or by setting the sdk.dir path in your project's local properties file at 'C:\Users\react\testing\MyApp\android\local.properties'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 50s
10 actionable tasks: 10 up-to-date
Error: C:\Users\react\testing\MyApp\android\gradlew.bat exited with non-zero code: 1
Error: C:\Users\react\testing\MyApp\android\gradlew.bat exited with non-zero code: 1
    at ChildProcess.completionListener (C:\Users\react\testing\MyApp\node_modules\@expo\cli\node_modules\@expo\spawn-async\build\spawnAsync.js:52:23)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at cp.emit (C:\Users\react\testing\MyApp\node_modules\@expo\cli\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
    ...
    at Object.spawnAsync [as default] (C:\Users\react\testing\MyApp\node_modules\@expo\cli\node_modules\@expo\spawn-async\build\spawnAsync.js:17:21)
    at spawnGradleAsync (C:\Users\react\testing\MyApp\node_modules\@expo\cli\build\src\start\platforms\android\gradle.js:72:46)
    at Object.assembleAsync (C:\Users\react\testing\MyApp\node_modules\@expo\cli\build\src\start\platforms\android\gradle.js:52:18)
    at runAndroidAsync (C:\Users\react\testing\MyApp\node_modules\@expo\cli\build\src\run\android\runAndroidAsync.js:36:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 ELIFECYCLE  Command failed with exit code 1.

C:\Users\react\testing\MyApp> cd android && rm -R .gradle && cd app && rm -R build
'rm' is not recognized as an internal or external command,
operable program or batch file.

**Comment by yjose** [comment]
@omarbenzi Apprently you didnt complete the envirement setup correctly 
```
SDK location not found. Define a valid SDK location with an ANDROID_HOME environment variable or by setting the sdk.dir path in your project's local properties file at 'C:\Users\react\testing\MyApp\android\local.properties'.
```
Make sure the [environment variables is configured correctly ](https://reactnative.dev/docs/environment-setup#:~:text=3.%20Configure%20the%20ANDROID_HOME%20environment%20variable)
