### ISSUE TITLE
tailwindcss(android) rebuilding... TypeError: style.declarations.findLast is not a function

### ISSUE THREAD

**Issue by coderDancer** [obytes/react-native-template-obytes#298]
# Summary:
<img width="969" alt="image" src="https://github.com/obytes/react-native-template-obytes/assets/22238447/0c95b084-5bc4-4cf3-802d-73a47cb765a1">

## Steps to reproduce:
tailwindcss(android) rebuilding... TypeError: style.declarations.findLast is not a function
    at setStyleForSelectorList (/Users/william/Documents/code/reference/react-native-template-obytes/node_modules/react-native-css-interop/src/css-to-rn/index.ts:358:54)
    at extractRule (/Users/william/Documents/code/reference/react-native-template-obytes/node_modules/react-native-css-interop/src/css-to-rn/index.ts:175:11)
    at Rule (/Users/william/Documents/code/reference/react-native-template-obytes/node_modules/react-native-css-interop/src/css-to-rn/index.ts:82:9)
    at cssToReactNativeRuntime (/Users/william/Documents/code/reference/react-native-template-obytes/node_modules/react-native-css-interop/src/css-to-rn/index.ts:76:15)
    at sendUpdate (/Users/william/Documents/code/reference/react-native-template-obytes/node_modules/react-native-css-interop/src/metro/poll-updates-server.ts:49:42)
    at Socket.<anonymous> (/Users/william/Documents/code/reference/react-native-template-obytes/node_modules/nativewind/src/metro/tailwind-cli.ts:106:17)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)

## Expected behavior:
first，this route - /Users/william/Documents/code/reference/react-native-template-obytes/node_modules/react-native-css-interop/src/css-to-rn/index.ts:358:54) is not exist
I try update tailwindcss@3.3.3，can't solve this problem

what sholud I do?

**Comment by eYdr1en** [comment]
You need to use node version 18 or above. Here is the issue in nativewind https://github.com/marklawlor/nativewind/issues/800

**Comment by coderDancer** [comment]
> You need to use node version 18 or above. Here is the issue in nativewind [marklawlor/nativewind#800](https://github.com/marklawlor/nativewind/issues/800)

wow，it solved my problem
Node version 18 or above
Thanks
