### ISSUE TITLE
yarn run web crashes with base installation

### ISSUE THREAD

**Issue by nikkwong** [obytes/react-native-template-obytes#50]
# Summary:

Did a clean install. Node v16. `yarn run web` fails to load anything in browser, resulting in:

```
constants.js:85 Uncaught TypeError: Cannot read properties of undefined (reading 'out')
    at ./node_modules/@gorhom/bottom-sheet/lib/module/constants.js (constants.js:85:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/@gorhom/bottom-sheet/lib/module/hooks/useScrollable.js (useScrollable.js:1:1)
    at __webpack_require__ (bootstrap:789:1)
```
&
```
index.js:1 ./node_modules/react-native-reanimated/lib/index.web.js 5:9
Module parse failed: Unexpected token (5:9)
File was processed with these loaders:
 * ./node_modules/@expo/webpack-config/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| export * from "./reanimated1";
| export * from "./reanimated2";
> export * as default from "./Animated";
```
& 
```
VM117:2 Uncaught ReferenceError: process is not defined
    at 4043 (<anonymous>:2:13168)
    at r (<anonymous>:2:306599)
    at 8048 (<anonymous>:2:9496)
    at r (<anonymous>:2:306599)
    at 8641 (<anonymous>:2:1379)
    at r (<anonymous>:2:306599)
    at <anonymous>:2:315627
    at <anonymous>:2:324225
    at <anonymous>:2:324229
    at e.onload (index.js:1:1)
```

## Steps to reproduce:

`yarn run web`

## Expected behavior:

Loading properly. Thank you!

**Comment by benszabo** [comment]
how were you able to resolve this? I am experiencing the same issue.

**Comment by silostack** [comment]
same here
