### ISSUE TITLE
Error while trying to run template

### ISSUE THREAD

**Issue by kabeza** [obytes/react-native-template-obytes#8]
Hi
I've got an error while trying to run the template. Its kinda weird because I can run other projects fine, etc.

Log

```
yarn run v1.22.17
$ react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1033 file(s) to forward-jetify. Using 6 workers...
info JS server already running.
info Installing the app...

> Configure project :react-native-mmkv
MMKV: node_modules/ found at: /home/reactnative/obytes/template/node_modules

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-mmkv'.
> com.android.builder.errors.EvalIssueException: NDK at /home/enrique/Android/Sdk/ndk/21.4.7075529 did not have a source.properties file

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-mmkv'.
> com.android.builder.errors.EvalIssueException: NDK at /home/enrique/Android/Sdk/ndk/21.4.7075529 did not have a source.properties file

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

    at makeError (/home/enrique/reactnative/obytes/template/node_modules/execa/index.js:174:9)
    at /home/enrique/reactnative/obytes/template/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/home/enrique/reactnative/obytes/template/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:106:5)
    at async Command.handleAction (/home/enrique/reactnative/obytes/template/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

React-native info

```
info Fetching system and libraries information...
System:
    OS: Linux 5.4 elementary OS 5.1.7 Hera
    CPU: (6) x64 Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz
    Memory: 512.02 MB / 15.50 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 16.13.2 - /usr/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 8.3.1 - /usr/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: AI-203.7717.56.2031.7784292
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.1 => 0.67.1 
  npmGlobalPackages:
    *react-native*: Not Found

```

Thanks for any tip you can give me

**Comment by yjose** [comment]
hmm the logs look weird as the `obytes/template/` shouldn't appear to you 
This issue should happen if you have an old react-native CLI installed globally, can you please remove it using
```
npm uninstall -g react-native-cli
```
now you can run
```
npx react-native init MyApp --template https://github.com/obytes/react-native-template-obytes
```
and should work correctly, please let me know if the issue still persists even after removing the global CLI

**Comment by kabeza** [comment]
Hi
Its very weird. I think I've done already that, because I already have the react-community-cli installed (latest version)
If I throw **react-native --version** I get
`6.2.0`

When I exec **sudo npm uninstall -g react-native-cli**
```
up to date, audited 1 package in 212ms
found 0 vulnerabilities
```

After this, I erased the obytes folder (i first got it cloning repository) and did again:

1. executed without errors:
`npx react-native init MyApp --template https://github.com/obytes/react-native-template-obytes`

2. run **npx react-native run-android** and got this (similar to first post)

```
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1033 file(s) to forward-jetify. Using 6 workers...
info JS server already running.
info Launching emulator...
info Successfully launched emulator.
info Installing the app...
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :react-native-mmkv
MMKV: node_modules/ found at: /home/enrique/reactnative/MyApp/node_modules

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-mmkv'.
> com.android.builder.errors.EvalIssueException: NDK at /home/enrique/Android/Sdk/ndk/21.4.7075529 did not have a source.properties file

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-mmkv'.
> com.android.builder.errors.EvalIssueException: NDK at /home/enrique/Android/Sdk/ndk/21.4.7075529 did not have a source.properties file

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s

    at makeError (/home/enrique/reactnative/MyApp/node_modules/execa/index.js:174:9)
    at /home/enrique/reactnative/MyApp/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/home/enrique/reactnative/MyApp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:106:5)
    at async Command.handleAction (/home/enrique/reactnative/MyApp/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.


```

**Comment by yjose** [comment]
@kabeza  same as #9  you should install NDK for android

**Comment by kabeza** [comment]
I have NDK installed
Will try to debug it and report any solution (in case I success)

![imagen_0256](https://user-images.githubusercontent.com/274856/152157147-c710f9b6-510b-4295-b661-fad6bb78155e.jpg)

**Comment by kabeza** [comment]
Ok I give up
I installed the updates from SDK Manager, NDK, CMake, etc.
Then restarted, executed again **npx react-native run-android** but keep getting the same error.

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-mmkv'.
> com.android.builder.errors.EvalIssueException: NDK at /home/enrique/Android/Sdk/ndk/21.4.7075529 did not have a source.properties file
```

Hope someone can later show some light to fix that error

**Comment by kabeza** [comment]
All working fine. Thanks !

**Comment by yjose** [comment]
thank you @kabeza

**Comment by yjose** [comment]
#9
