### ISSUE TITLE
Error when executing npx react-native run-android

### ISSUE THREAD

**Issue by ahdidou-mohamed** [obytes/react-native-template-obytes#9]
**Problem description**
After setting up a project using the template I tried to run the project using this command as suggested by the CLI 
`npx react-native run-android`

Before that I launched the emulator in my machine

**Logs**

```
❯  npx react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1033 file(s) to forward-jetify. Using 16 workers...
info Starting JS server...
info Installing the app...
Starting a Gradle Daemon, 1 busy and 2 incompatible Daemons could not be reused, use --status for details

> Configure project :react-native-mmkv
MMKV: node_modules/ found at: /Users/mohamed/Documents/Workspace/ReactNative/MyAppp/node_modules

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-mmkv'.
> com.android.builder.errors.EvalIssueException: NDK at /Users/mohamed/Library/Android/sdk/ndk/21.4.7075529 did not have a source.properties file

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-mmkv'.
> com.android.builder.errors.EvalIssueException: NDK at /Users/mohamed/Library/Android/sdk/ndk/21.4.7075529 did not have a source.properties file

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s

    at makeError (/Users/mohamed/Documents/Workspace/ReactNative/MyAppp/node_modules/execa/index.js:174:9)
    at /Users/mohamed/Documents/Workspace/ReactNative/MyAppp/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/mohamed/Documents/Workspace/ReactNative/MyAppp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:106:5)
    at async Command.handleAction (/Users/mohamed/Documents/Workspace/ReactNative/MyAppp/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.
```

**Comment by yjose** [comment]
Hey @ahdidou-mohamed ,  make sure the NDK is already installed  https://github.com/mrousavy/react-native-mmkv/issues/140

**Comment by yjose** [comment]
check #8
